CREATE TABLE Dosar11(id TEXT NOT NULL PRIMARY KEY, year INTEGER NOT NULL, number INTEGER NOT NULL, depun DATE DEFAULT NULL, solutie DATE DEFAULT NULL, ordin TEXT DEFAULT NULL, anexa INTEGER DEFAULT NULL, cminori INTEGER DEFAULT NULL, result INTEGER DEFAULT NULL, termen DATE DEFAULT NULL, suplimentar INTEGER DEFAULT False, juramat DATE DEFAULT NULL, refuz INTEGER DEFAULT 0);
CREATE TABLE Termen11(id TEXT, termen DATE, stadiu DATE, UNIQUE(id, termen) );
CREATE TABLE Refuz11(id TEXT PRIMARY KEY, ordin TEXT NOT NULL, depun DATE, solutie DATE);
CREATE INDEX IF NOT EXISTS idx_refuz11_ordin ON Refuz11(ordin);
CREATE INDEX IF NOT EXISTS idx_dosar11_ordin ON Dosar11(ordin) WHERE ordin IS NOT NULL;

